import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" data-theme="dark" className="w-dvw h-dvh bg-neutral-200 dark:bg-neutral-800" suppressHydrationWarning>
      <body className={inter.className}>
        <script dangerouslySetInnerHTML={{__html: `if (localStorage.getItem("theme") === null) {document.documentElement.setAttribute("data-theme", "light");} else {document.documentElement.setAttribute("data-theme",localStorage.getItem("theme"));}`}}></script>
        {children}
      </body>
    </html>
  );
}
